// Generated by comark-content — do not edit by hand.
import type { QueryRowBase } from 'comark-content'

export interface DefaultData {
  name: string;
  tagline: string;
  created: string;
  rules: Array<string>;
  updated?: string;
}

export interface DefaultRow extends QueryRowBase {
  'data.name': string;
  'data.tagline': string;
  'data.created': string;
  'data.rules': Array<string>;
  'data.updated'?: string;
}

declare module 'comark-content' {
  interface ContentRegistry {
    'default': { data: DefaultData; row: DefaultRow }
  }
  interface ContentPathsRegistry {
    'default': {
      '/_template': DefaultData
      '/ai-allowed': DefaultData
      '/ai-disallowed': DefaultData
      '/human-responsible': DefaultData
    }
  }
}
